/*
Copyright (C) 2017-2026 Topological Manifold

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

#version 460

#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT acceleration_structure;
layout(set = 0, binding = 1, rgba32f) writeonly restrict uniform image2D image;

layout(location = 0) rayPayloadEXT vec3 hit_value;

void main()
{
        const float t_min = 0.001;
        const float t_max = 1000;

        const vec2 pixel_center = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
        const vec2 d = 2 * pixel_center / vec2(gl_LaunchSizeEXT.xy) - 1;

        const vec3 org = vec3(0, 0, -1);
        const vec3 dir = normalize(vec3(d.x, d.y, 1));

        hit_value = vec3(0);

        traceRayEXT(acceleration_structure, gl_RayFlagsOpaqueEXT, 0xFF, 0, 0, 0, org, t_min, dir, t_max, 0);

        imageStore(image, ivec2(gl_LaunchIDEXT.xy), vec4(hit_value, 0));
}
