#  FFTW_FOUND
#  FFTW_INCLUDE_DIRS
#  FFTW_LIBRARIES
#  FFTW_THREAD_LIBRARIES

if (FFTW_INCLUDE_DIRS AND FFTW_LIBRARIES AND FFTW_THREAD_LIBRARIES)
        set(FFTW_FIND_QUIETLY TRUE)
endif()

find_library(FFTW_LIBRARIES NAMES fftw3f libfftw3f)
find_library(FFTW_THREAD_LIBRARIES NAMES fftw3f_threads libfftw3f_threads)
find_path(FFTW_INCLUDE_DIRS NAMES fftw3.h)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(FFTW DEFAULT_MSG FFTW_INCLUDE_DIRS FFTW_LIBRARIES FFTW_THREAD_LIBRARIES)
mark_as_advanced(FFTW_INCLUDE_DIRS FFTW_LIBRARIES FFTW_THREAD_LIBRARIES)
